[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
newp = "AbgLLwQAE3TwCc9qvHk3YtaTGqNzCU1URUixX4P4yRe4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
